from typing import Any, Protocol


class MinifluxGatewayProtocol(Protocol):
    def me(self): ...

    def get_entries(self, **kwargs): ...

    def update_entry(self, entry_id, **kwargs): ...

    def get_feeds(self): ...

    def create_feed(self, **kwargs): ...

    def refresh_feed(self, feed_id): ...


class LLMGatewayProtocol(Protocol):
    def get_result(self, prompt: str, request: str, logger: Any = None): ...
